name: Front CI/CD with GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Build Production Bundle
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout Original Repository
        uses: actions/checkout@v2
        with:
          repository: DevTeamOss/OpenSource-Supporter-FrontEnd
          ref: main
          path: original_repo  # 다른 디렉토리에 원본 레포지터리를 체크아웃합니다.
        
      - name: Copy .env file
        run: cp OpenSource-Supporter-FrontEnd/.env .   # 원본 레포지터리의 .env 파일을 현재 디렉토리로 복사합니다.
        
      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > OSSKey.pem
          chmod 600 OSSKey.pem
          ssh -i OSSKey.pem -o StrictHostKeyChecking=no ubuntu@ec2-13-124-206-202.ap-northeast-2.compute.amazonaws.com "
            cd OpenSource-Supporter-FrontEnd &&
            cp .env ~/backup_env &&
            git reset --hard origin/main &&
            cp ~/backup_env .env &&
            sudo cp -r dist/* /var/www/html/ &&
            sudo systemctl restart nginx
          "
            rm -f OSSKey.pem
