name: Front CI/CD with GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Build Production Bundle
        run: npm run build
        
      - name: Deploy to EC2
        run: |
          sudo apt-get update && sudo apt-get install -y openssh-client
          ssh -i ${{ secrets.EC2_SSH_KEY }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "cd OpenSource-Supporter-FrontEnd && git pull origin main && sudo cp -r dist/* /var/www/html/ && sudo systemctl restart nginx"
